name: Codecov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch
        uses: actions/checkout@master
      - name: Test
        run: |
          gcov -abcfu pom.xml
      - name: Upload
        uses: codecov/codecov-action@v2
        with:
          files: ./pom.xml.gcov
